spring:
    application:
        name: kkfs

kkfs:
    path: ${user.home}/kkfs
    syncBackup: false
    autoMd5: true
    backupUrl: http://localhost:8091/upload
    downloadUrl: http://localhost:8090/download
    group: C8090

rocketmq:
    name-server: localhost:9876
    producer:
        group: dev1
        send-message-timeout: 3000
        retry-times-when-send-failed: 3
        retry-times-when-send-async-failed: 3

server:
    port: 8090
